# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='fisk.broker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x0b\x66isk.broker\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n\x0e\x43\x61ndlesRequest\x12\x18\n\x10instrument_token\x18\x01 \x01(\t\x12+\n\x08interval\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12-\n\tfrom_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07to_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xdf\x01\n\x0f\x43\x61ndlesResponse\x12\x18\n\x10instrument_token\x18\x01 \x01(\t\x12+\n\x08interval\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12-\n\tfrom_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07to_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x07\x63\x61ndles\x18\x05 \x03(\x0b\x32\x18.fisk.broker.Candlestick\"\x84\x01\n\x0b\x43\x61ndlestick\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04open\x18\x02 \x01(\x05\x12\x0c\n\x04high\x18\x03 \x01(\x05\x12\x0b\n\x03low\x18\x04 \x01(\x05\x12\r\n\x05\x63lose\x18\x05 \x01(\x05\x12\x0e\n\x06volume\x18\x06 \x01(\x05\x32L\n\x04\x44\x61ta\x12\x44\n\x07\x43\x61ndles\x12\x1b.fisk.broker.CandlesRequest\x1a\x1c.fisk.broker.CandlesResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CANDLESREQUEST = _descriptor.Descriptor(
  name='CandlesRequest',
  full_name='fisk.broker.CandlesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_token', full_name='fisk.broker.CandlesRequest.instrument_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='fisk.broker.CandlesRequest.interval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_date', full_name='fisk.broker.CandlesRequest.from_date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_date', full_name='fisk.broker.CandlesRequest.to_date', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=272,
)


_CANDLESRESPONSE = _descriptor.Descriptor(
  name='CandlesResponse',
  full_name='fisk.broker.CandlesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_token', full_name='fisk.broker.CandlesResponse.instrument_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='fisk.broker.CandlesResponse.interval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_date', full_name='fisk.broker.CandlesResponse.from_date', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_date', full_name='fisk.broker.CandlesResponse.to_date', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='candles', full_name='fisk.broker.CandlesResponse.candles', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=498,
)


_CANDLESTICK = _descriptor.Descriptor(
  name='Candlestick',
  full_name='fisk.broker.Candlestick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='fisk.broker.Candlestick.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='fisk.broker.Candlestick.open', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='fisk.broker.Candlestick.high', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='fisk.broker.Candlestick.low', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='fisk.broker.Candlestick.close', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='fisk.broker.Candlestick.volume', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=633,
)

_CANDLESREQUEST.fields_by_name['interval'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CANDLESREQUEST.fields_by_name['from_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CANDLESREQUEST.fields_by_name['to_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CANDLESRESPONSE.fields_by_name['interval'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CANDLESRESPONSE.fields_by_name['from_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CANDLESRESPONSE.fields_by_name['to_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CANDLESRESPONSE.fields_by_name['candles'].message_type = _CANDLESTICK
_CANDLESTICK.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['CandlesRequest'] = _CANDLESREQUEST
DESCRIPTOR.message_types_by_name['CandlesResponse'] = _CANDLESRESPONSE
DESCRIPTOR.message_types_by_name['Candlestick'] = _CANDLESTICK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CandlesRequest = _reflection.GeneratedProtocolMessageType('CandlesRequest', (_message.Message,), dict(
  DESCRIPTOR = _CANDLESREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:fisk.broker.CandlesRequest)
  ))
_sym_db.RegisterMessage(CandlesRequest)

CandlesResponse = _reflection.GeneratedProtocolMessageType('CandlesResponse', (_message.Message,), dict(
  DESCRIPTOR = _CANDLESRESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:fisk.broker.CandlesResponse)
  ))
_sym_db.RegisterMessage(CandlesResponse)

Candlestick = _reflection.GeneratedProtocolMessageType('Candlestick', (_message.Message,), dict(
  DESCRIPTOR = _CANDLESTICK,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:fisk.broker.Candlestick)
  ))
_sym_db.RegisterMessage(Candlestick)



_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='fisk.broker.Data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=635,
  serialized_end=711,
  methods=[
  _descriptor.MethodDescriptor(
    name='Candles',
    full_name='fisk.broker.Data.Candles',
    index=0,
    containing_service=None,
    input_type=_CANDLESREQUEST,
    output_type=_CANDLESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
